# Generated by Django 3.1.2 on 2021-11-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.TextField(default='0')),
                ('title', models.TextField(default='Nameless')),
                ('artist', models.TextField(default='Unknown')),
                ('image', models.ImageField(default='https://cdn.pixabay.com/photo/2014/04/02/10/57/vinyl-305025_640.png', upload_to='')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
                ('audio_link', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(default='duration', max_length=20)),
            ],
        ),
    ]
