# Generated by Django 3.1.2 on 2021-11-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='index',
        ),
        migrations.AddField(
            model_name='song',
            name='stt',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
