# Generated by Django 3.2.9 on 2021-11-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relax', '0002_auto_20211114_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='stt',
            field=models.TextField(default=''),
        ),
    ]
