# Generated by Django 3.1.2 on 2021-11-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relax', '0003_auto_20211114_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='stt',
            field=models.TextField(default='', unique=True),
        ),
    ]
