# Generated by Django 3.2.9 on 2021-11-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relax', '0003_auto_20211118_2001'),
        ('relax', '0004_auto_20211114_1459'),
    ]

    operations = [
    ]
