# Generated by Django 3.2.9 on 2021-11-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relax', '0005_merge_0003_auto_20211118_2001_0004_auto_20211114_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='stt',
            field=models.TextField(default='', unique=True),
        ),
    ]
